main: ${project.package}.Main
name: ${project.name}

version: ${project.version}
description: ${project.description}
website: ${project.url}

authors:
  - ArtformGames

api-version: 1.16

depend:
  - ArtCore
  - LuckPerms

softdepend:
  - PlaceholderAPI

permissions:
  "usersuffix.use":
    default: true